apiVersion: v1
kind: Secret
metadata:
  name: webhook-config
  namespace: monitoring
type: Opaque
stringData:
  url: "https://your-webhook-endpoint.com/alerts"
  auth-header: "Bearer your-secret-token-here"